name: Self-Hosted Runner Example

on:
  push:
    branches: [ main ]

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    steps:
      - name: Echo on Self-Hosted Runner
        run: echo "This job is running on a self-hosted runner!"
