name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your production branch
      - dev   # Replace with your development branch

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Environment
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and Push Docker Image
      env:
        REPOSITORY: your-docker-hub-username/image-name
        COMMIT_HASH: ${{ github.sha }}
      run: |
        # Build and tag the Docker image
        docker build -t $REPOSITORY:$COMMIT_HASH .
        
        # Additional tagging
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          docker tag $REPOSITORY:$COMMIT_HASH $REPOSITORY:stable
        elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          docker tag $REPOSITORY:$COMMIT_HASH $REPOSITORY:dev
        fi
        
        # Push the Docker image
        docker push --all-tags $REPOSITORY

    - name: Increase version in package.json
      run: npm version patch -m "Increase version to %s"
